//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deveel.Data {
	
	
	public partial class SqlState {
		
		static SqlState() {
			AddState("ok", 0, "00", "000");
		}
	}
}
