/* Generated By:CSharpCC: Do not edit this line. SQLConstants.cs */
namespace Deveel.Data.Sql{
internal  class SQLConstants {

  public const int EOF = 0;
  public const int STAR = 7;
  public const int ASSIGNMENT = 8;
  public const int EQUALS = 9;
  public const int GR = 10;
  public const int LE = 11;
  public const int GREQ = 12;
  public const int LEEQ = 13;
  public const int NOTEQ = 14;
  public const int DIVIDE = 15;
  public const int ADD = 16;
  public const int SUBTRACT = 17;
  public const int CONCAT = 18;
  public const int MODULUS = 19;
  public const int SEMICOLUMN = 20;
  public const int BOOLEAN_LITERAL = 21;
  public const int NULL_LITERAL = 22;
  public const int REGEX_LITERAL = 23;
  public const int DROP = 24;
  public const int SHOW = 25;
  public const int ALTER = 26;
  public const int SELECT = 27;
  public const int UPDATE = 28;
  public const int CREATE = 29;
  public const int DELETE = 30;
  public const int INSERT = 31;
  public const int COMMIT = 32;
  public const int COMPACT = 33;
  public const int EXPLAIN = 34;
  public const int ROLLBACK = 35;
  public const int OPTIMIZE = 36;
  public const int DESCRIBE = 37;
  public const int SHUTDOWN = 38;
  public const int IS = 39;
  public const int AS = 40;
  public const int ON = 41;
  public const int IF = 42;
  public const int TO = 43;
  public const int NO = 44;
  public const int ALL = 45;
  public const int ANY = 46;
  public const int END = 47;
  public const int SET = 48;
  public const int USE = 49;
  public const int ASC = 50;
  public const int OLD = 51;
  public const int NEW = 52;
  public const int SQLADD = 53;
  public const int FOR = 54;
  public const int ROW = 55;
  public const int CASE = 56;
  public const int ELSE = 57;
  public const int EACH = 58;
  public const int CALL = 59;
  public const int BOTH = 60;
  public const int SOME = 61;
  public const int FROM = 62;
  public const int LEFT = 63;
  public const int DESC = 64;
  public const int INTO = 65;
  public const int JOIN = 66;
  public const int TRIM = 67;
  public const int VIEW = 68;
  public const int LOCK = 69;
  public const int WITH = 70;
  public const int TYPE = 71;
  public const int USER = 72;
  public const int CAST = 73;
  public const int LONG = 74;
  public const int NAME = 75;
  public const int OPEN = 76;
  public const int THEN = 77;
  public const int WHEN = 78;
  public const int AFTER = 79;
  public const int START = 80;
  public const int COUNT = 81;
  public const int WHERE = 82;
  public const int CYCLE = 83;
  public const int CACHE = 84;
  public const int RIGHT = 85;
  public const int TABLE = 86;
  public const int LIMIT = 87;
  public const int INNER = 88;
  public const int INDEX = 89;
  public const int CLOSE = 90;
  public const int CROSS = 91;
  public const int OUTER = 92;
  public const int CHECK = 93;
  public const int FINAL = 94;
  public const int UNDER = 95;
  public const int USING = 96;
  public const int UNION = 97;
  public const int GRANT = 98;
  public const int USAGE = 99;
  public const int FETCH = 100;
  public const int SQLRETURN = 101;
  public const int BEFORE = 102;
  public const int UNLOCK = 103;
  public const int CURSOR = 104;
  public const int SCROLL = 105;
  public const int ACTION = 106;
  public const int GROUPS = 107;
  public const int REVOKE = 108;
  public const int OPTION = 109;
  public const int CSHARP = 110;
  public const int PUBLIC = 111;
  public const int EXCEPT = 112;
  public const int IGNORE = 113;
  public const int SCHEMA = 114;
  public const int EXISTS = 115;
  public const int SOUNDS = 116;
  public const int VALUES = 117;
  public const int HAVING = 118;
  public const int UNIQUE = 119;
  public const int SQLCOLUMN = 120;
  public const int RETURNS = 121;
  public const int ACCOUNT = 122;
  public const int DECLARE = 123;
  public const int LEADING = 124;
  public const int NATURAL = 125;
  public const int BETWEEN = 126;
  public const int TRIGGER = 127;
  public const int SQLDEFAULT = 128;
  public const int VARYING = 129;
  public const int EXECUTE = 130;
  public const int CALLBACK = 131;
  public const int MINVALUE = 132;
  public const int MAXVALUE = 133;
  public const int FUNCTION = 134;
  public const int CONSTANT = 135;
  public const int READONLY = 136;
  public const int SEQUENCE = 137;
  public const int RESTRICT = 138;
  public const int PASSWORD = 139;
  public const int TRAILING = 140;
  public const int GROUPBY = 141;
  public const int EXTRACT = 142;
  public const int ORDERBY = 143;
  public const int DEFERRED = 144;
  public const int EXTERNAL = 145;
  public const int IDENTITY = 146;
  public const int DISTINCT = 147;
  public const int LANGUAGE = 148;
  public const int INCREMENT = 149;
  public const int PROCEDURE = 150;
  public const int CHARACTER = 151;
  public const int CURRENTOF = 152;
  public const int IMMEDIATE = 153;
  public const int INITIALLY = 154;
  public const int TEMPORARY = 155;
  public const int INTERSECT = 156;
  public const int PRIVILEGES = 157;
  public const int CONSTRAINT = 158;
  public const int DEFERRABLE = 159;
  public const int REFERENCES = 160;
  public const int INSENSITIVE = 161;
  public const int PRIMARY = 162;
  public const int FOREIGN = 163;
  public const int KEY = 164;
  public const int INDEX_NONE = 165;
  public const int INDEX_BLIST = 166;
  public const int GROUPMAX = 167;
  public const int COLLATE = 168;
  public const int PRIMARY_STRENGTH = 169;
  public const int SECONDARY_STRENGTH = 170;
  public const int TERTIARY_STRENGTH = 171;
  public const int IDENTICAL_STRENGTH = 172;
  public const int NO_DECOMPOSITION = 173;
  public const int CANONICAL_DECOMPOSITION = 174;
  public const int FULL_DECOMPOSITION = 175;
  public const int BIT = 176;
  public const int DAY = 177;
  public const int INT = 178;
  public const int REAL = 179;
  public const int CLOB = 180;
  public const int BLOB = 181;
  public const int CHAR = 182;
  public const int TEXT = 183;
  public const int DATE = 184;
  public const int TIME = 185;
  public const int YEAR = 186;
  public const int HOUR = 187;
  public const int FLOAT = 188;
  public const int MONTH = 189;
  public const int SECOND = 190;
  public const int MINUTE = 191;
  public const int BIGINT = 192;
  public const int DOUBLE = 193;
  public const int STRING = 194;
  public const int BINARY = 195;
  public const int OBJECT = 196;
  public const int NUMERIC = 197;
  public const int DECIMAL = 198;
  public const int BOOLEAN = 199;
  public const int TINYINT = 200;
  public const int INTEGER = 201;
  public const int VARCHAR = 202;
  public const int SMALLINT = 203;
  public const int INTERVAL = 204;
  public const int VARBINARY = 205;
  public const int TIMESTAMP = 206;
  public const int LONGVARCHAR = 207;
  public const int LONGVARBINARY = 208;
  public const int TRANSACTIONISOLATIONLEVEL = 209;
  public const int AUTOCOMMIT = 210;
  public const int READCOMMITTED = 211;
  public const int READUNCOMMITTED = 212;
  public const int REPEATABLEREAD = 213;
  public const int SERIALIZABLE = 214;
  public const int FIRST = 215;
  public const int LAST = 216;
  public const int NEXT = 217;
  public const int PRIOR = 218;
  public const int ABSOLUTE = 219;
  public const int RELATIVE = 220;
  public const int CASCADE = 221;
  public const int CURRENT_TIME = 222;
  public const int CURRENT_DATE = 223;
  public const int CURRENT_TIMESTAMP = 224;
  public const int DBTIMEZONE = 225;
  public const int LIKE = 226;
  public const int REGEX = 227;
  public const int AND = 228;
  public const int OR = 229;
  public const int IN = 230;
  public const int NOT = 231;
  public const int NUMBER_LITERAL = 232;
  public const int STRING_LITERAL = 233;
  public const int QUOTED_VARIABLE = 234;
  public const int IDENTIFIER = 235;
  public const int DOT_DELIMINATED_REF = 236;
  public const int QUOTED_DELIMINATED_REF = 237;
  public const int OBJECT_ARRAY_REF = 238;
  public const int CTALIAS = 239;
  public const int GLOBVARIABLE = 240;
  public const int QUOTEDGLOBVARIABLE = 241;
  public const int NAMED_PARAMETER = 242;
  public const int PARAMETER_REF = 243;
  public const int NAMED_PARAMETER_PREFIX = 244;
  public const int VARIABLE_REF = 245;
  public const int LETTER = 246;
  public const int DIGIT = 247;

  public const int DEFAULT = 0;

  public readonly string[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"*\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<NOTEQ>",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"%\"",
    "\";\"",
    "<BOOLEAN_LITERAL>",
    "\"null\"",
    "<REGEX_LITERAL>",
    "\"drop\"",
    "\"show\"",
    "\"alter\"",
    "\"select\"",
    "\"update\"",
    "\"create\"",
    "\"delete\"",
    "\"insert\"",
    "\"commit\"",
    "\"compact\"",
    "\"explain\"",
    "\"rollback\"",
    "\"optimize\"",
    "\"describe\"",
    "\"shutdown\"",
    "\"is\"",
    "\"as\"",
    "\"on\"",
    "\"if\"",
    "\"to\"",
    "\"no\"",
    "\"all\"",
    "\"any\"",
    "\"end\"",
    "\"set\"",
    "\"use\"",
    "\"asc\"",
    "\"old\"",
    "\"new\"",
    "\"add\"",
    "\"for\"",
    "\"row\"",
    "\"case\"",
    "\"else\"",
    "\"each\"",
    "\"call\"",
    "\"both\"",
    "\"some\"",
    "\"from\"",
    "\"left\"",
    "\"desc\"",
    "\"into\"",
    "\"join\"",
    "\"trim\"",
    "\"view\"",
    "\"lock\"",
    "\"with\"",
    "\"type\"",
    "\"user\"",
    "\"cast\"",
    "\"long\"",
    "\"name\"",
    "\"open\"",
    "\"then\"",
    "\"when\"",
    "\"after\"",
    "\"start\"",
    "\"count\"",
    "\"where\"",
    "\"cycle\"",
    "\"cache\"",
    "\"right\"",
    "\"table\"",
    "\"limit\"",
    "\"inner\"",
    "\"index\"",
    "\"close\"",
    "\"cross\"",
    "\"outer\"",
    "\"check\"",
    "\"final\"",
    "\"under\"",
    "\"using\"",
    "\"union\"",
    "\"grant\"",
    "\"usage\"",
    "\"fetch\"",
    "\"return\"",
    "\"before\"",
    "\"unlock\"",
    "\"cursor\"",
    "\"scroll\"",
    "\"action\"",
    "\"groups\"",
    "\"revoke\"",
    "\"option\"",
    "\"csharp\"",
    "\"public\"",
    "\"except\"",
    "\"ignore\"",
    "\"schema\"",
    "\"exists\"",
    "\"sounds\"",
    "\"values\"",
    "\"having\"",
    "\"unique\"",
    "\"column\"",
    "\"returns\"",
    "\"account\"",
    "\"declare\"",
    "\"leading\"",
    "\"natural\"",
    "\"between\"",
    "\"trigger\"",
    "\"default\"",
    "\"varying\"",
    "\"execute\"",
    "\"callback\"",
    "\"minvalue\"",
    "\"maxvalue\"",
    "\"function\"",
    "\"constant\"",
    "\"readonly\"",
    "\"sequence\"",
    "\"restrict\"",
    "\"password\"",
    "\"trailing\"",
    "\"group by\"",
    "\"extract\"",
    "\"order by\"",
    "\"deferred\"",
    "\"external\"",
    "\"identity\"",
    "\"distinct\"",
    "\"language\"",
    "\"increment\"",
    "\"procedure\"",
    "\"character\"",
    "\"current of\"",
    "\"immediate\"",
    "\"initially\"",
    "\"temporary\"",
    "\"intersect\"",
    "\"privileges\"",
    "\"constraint\"",
    "\"deferrable\"",
    "\"references\"",
    "\"insensitive\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"index_none\"",
    "\"index_blist\"",
    "\"group max\"",
    "\"collate\"",
    "\"primary_strength\"",
    "\"secondary_strength\"",
    "\"tertiary_strength\"",
    "\"identical_strength\"",
    "\"no_decomposition\"",
    "\"canonical_decomposition\"",
    "\"full_decomposition\"",
    "\"bit\"",
    "\"day\"",
    "\"int\"",
    "\"real\"",
    "\"clob\"",
    "\"blob\"",
    "\"char\"",
    "\"text\"",
    "\"date\"",
    "\"time\"",
    "\"year\"",
    "\"hour\"",
    "\"float\"",
    "\"month\"",
    "\"second\"",
    "\"minute\"",
    "\"bigint\"",
    "\"double\"",
    "\"string\"",
    "\"binary\"",
    "\"object\"",
    "\"numeric\"",
    "\"decimal\"",
    "\"bool\"",
    "\"tinyint\"",
    "\"integer\"",
    "\"varchar\"",
    "\"smallint\"",
    "\"interval\"",
    "\"varbinary\"",
    "\"timestamp\"",
    "\"longvarchar\"",
    "\"longvarbinary\"",
    "\"transaction isolation level\"",
    "\"auto commit\"",
    "\"read committed\"",
    "\"read uncommitted\"",
    "\"repeatable read\"",
    "\"serializable\"",
    "\"first\"",
    "\"last\"",
    "\"next\"",
    "\"prior\"",
    "\"absolute\"",
    "\"relative\"",
    "\"cascade\"",
    "\"current_time\"",
    "\"current_date\"",
    "\"current_timestamp\"",
    "\"dbtimezone\"",
    "\"like\"",
    "\"regex\"",
    "\"and\"",
    "\"or\"",
    "\"in\"",
    "\"not\"",
    "<NUMBER_LITERAL>",
    "<STRING_LITERAL>",
    "<QUOTED_VARIABLE>",
    "<IDENTIFIER>",
    "<DOT_DELIMINATED_REF>",
    "<QUOTED_DELIMINATED_REF>",
    "<OBJECT_ARRAY_REF>",
    "<CTALIAS>",
    "<GLOBVARIABLE>",
    "<QUOTEDGLOBVARIABLE>",
    "<NAMED_PARAMETER>",
    "\"?\"",
    "\"@\"",
    "<VARIABLE_REF>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
}
