// 
//  Copyright 2010  Deveel
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

using System;

namespace Deveel.Data {
	///<summary>
	///  A trigger event represents a high level action that occured 
	/// in the database.
	///</summary>
	/// <remarks>
	/// A trigger event is generated by the SQL interpreter on evaluation 
	/// of curtain types of queries.
	/// </remarks>
	public class TriggerEvent {
		/// <summary>
		/// The type of this event.
		/// </summary>
		private readonly TriggerEventType type;

		/// <summary>
		/// The source of the trigger (eg. the table name).
		/// </summary>
		private readonly String source;

		/// <summary>
		/// The number of times this event was fired.
		/// </summary>
		private readonly int count;

		public TriggerEvent(TriggerEventType type, String source, int count) {
			this.type = type;
			this.source = source;
			this.count = count;
		}

		public TriggerEvent(TriggerEventType type, String source)
			: this(type, source, 1) {
		}

		/// <summary>
		/// Returns the type of this event.
		/// </summary>
		public TriggerEventType Type {
			get { return type; }
		}

		///<summary>
		/// Returns the source of this event.
		///</summary>
		public string Source {
			get { return source; }
		}

		/// <summary>
		/// Returns the number of times this event was fired.
		/// </summary>
		public int Count {
			get { return count; }
		}
	}
}