// 
//  TriggerEvent.cs
//  
//  Author:
//       Antonello Provenzano <antonello@deveel.com>
//       Tobias Downer <toby@mckoi.com>
//  
//  Copyright (c) 2009 Deveel
// 
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
// 
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
// 
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System;

namespace Deveel.Data {
	///<summary>
	///  A trigger event represents a high level action that occured 
	/// in the database.
	///</summary>
	/// <remarks>
	/// A trigger event is generated by the SQL interpreter on evaluation 
	/// of curtain types of queries.
	/// </remarks>
	public class TriggerEvent {
		/// <summary>
		/// The type of this event.
		/// </summary>
		private readonly TriggerEventType type;

		/// <summary>
		/// The source of the trigger (eg. the table name).
		/// </summary>
		private readonly String source;

		/// <summary>
		/// The number of times this event was fired.
		/// </summary>
		private readonly int count;

		public TriggerEvent(TriggerEventType type, String source, int count) {
			this.type = type;
			this.source = source;
			this.count = count;
		}

		public TriggerEvent(TriggerEventType type, String source)
			: this(type, source, 1) {
		}

		/// <summary>
		/// Returns the type of this event.
		/// </summary>
		public TriggerEventType Type {
			get { return type; }
		}

		///<summary>
		/// Returns the source of this event.
		///</summary>
		public string Source {
			get { return source; }
		}

		/// <summary>
		/// Returns the number of times this event was fired.
		/// </summary>
		public int Count {
			get { return count; }
		}
	}
}