//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deveel.Math.Deveel.Math {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deveel.Math.Deveel.Math.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rounding mode.
        /// </summary>
        internal static string math00 {
            get {
                return ResourceManager.GetString("math00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power of ten too big.
        /// </summary>
        internal static string math01 {
            get {
                return ResourceManager.GetString("math01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale out of range..
        /// </summary>
        internal static string math02 {
            get {
                return ResourceManager.GetString("math02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite or NaN.
        /// </summary>
        internal static string math03 {
            get {
                return ResourceManager.GetString("math03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero.
        /// </summary>
        internal static string math04 {
            get {
                return ResourceManager.GetString("math04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-terminating decimal expansion; no exact representable decimal result..
        /// </summary>
        internal static string math05 {
            get {
                return ResourceManager.GetString("math05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division impossible.
        /// </summary>
        internal static string math06 {
            get {
                return ResourceManager.GetString("math06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation.
        /// </summary>
        internal static string math07 {
            get {
                return ResourceManager.GetString("math07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding necessary.
        /// </summary>
        internal static string math08 {
            get {
                return ResourceManager.GetString("math08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow.
        /// </summary>
        internal static string math09 {
            get {
                return ResourceManager.GetString("math09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underflow.
        /// </summary>
        internal static string math0A {
            get {
                return ResourceManager.GetString("math0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null unscaled value.
        /// </summary>
        internal static string math0B {
            get {
                return ResourceManager.GetString("math0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits &lt; 0.
        /// </summary>
        internal static string math0C {
            get {
                return ResourceManager.GetString("math0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null RoundingMode.
        /// </summary>
        internal static string math0D {
            get {
                return ResourceManager.GetString("math0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad string format.
        /// </summary>
        internal static string math0E {
            get {
                return ResourceManager.GetString("math0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad precision value.
        /// </summary>
        internal static string math0F {
            get {
                return ResourceManager.GetString("math0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null roundingMode.
        /// </summary>
        internal static string math10 {
            get {
                return ResourceManager.GetString("math10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radix out of range.
        /// </summary>
        internal static string math11 {
            get {
                return ResourceManager.GetString("math11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero length BigInteger.
        /// </summary>
        internal static string math12 {
            get {
                return ResourceManager.GetString("math12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signum value.
        /// </summary>
        internal static string math13 {
            get {
                return ResourceManager.GetString("math13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signum-magnitude mismatch.
        /// </summary>
        internal static string math14 {
            get {
                return ResourceManager.GetString("math14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative bit address.
        /// </summary>
        internal static string math15 {
            get {
                return ResourceManager.GetString("math15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative exponent.
        /// </summary>
        internal static string math16 {
            get {
                return ResourceManager.GetString("math16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigInteger divide by zero.
        /// </summary>
        internal static string math17 {
            get {
                return ResourceManager.GetString("math17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigInteger: modulus not positive.
        /// </summary>
        internal static string math18 {
            get {
                return ResourceManager.GetString("math18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BigInteger not invertible..
        /// </summary>
        internal static string math19 {
            get {
                return ResourceManager.GetString("math19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start &lt; 0: {0}.
        /// </summary>
        internal static string math1A {
            get {
                return ResourceManager.GetString("math1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numBits must be non-negative.
        /// </summary>
        internal static string math1B {
            get {
                return ResourceManager.GetString("math1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitLength &lt; 2.
        /// </summary>
        internal static string math1C {
            get {
                return ResourceManager.GetString("math1C", resourceCulture);
            }
        }
    }
}
