/* Generated By:CSharpCC: Do not edit this line. SQLConstants.cs */
namespace Deveel.Data.Sql{
public class SQLConstants {

  internal const int EOF = 0;
  internal const int STAR = 7;
  internal const int ASSIGNMENT = 8;
  internal const int EQUALS = 9;
  internal const int GR = 10;
  internal const int LE = 11;
  internal const int GREQ = 12;
  internal const int LEEQ = 13;
  internal const int NOTEQ = 14;
  internal const int DIVIDE = 15;
  internal const int ADD = 16;
  internal const int SUBTRACT = 17;
  internal const int CONCAT = 18;
  internal const int BOOLEAN_LITERAL = 19;
  internal const int NULL_LITERAL = 20;
  internal const int REGEX_LITERAL = 21;
  internal const int DROP = 22;
  internal const int SHOW = 23;
  internal const int ALTER = 24;
  internal const int SELECT = 25;
  internal const int UPDATE = 26;
  internal const int CREATE = 27;
  internal const int DELETE = 28;
  internal const int INSERT = 29;
  internal const int COMMIT = 30;
  internal const int COMPACT = 31;
  internal const int EXPLAIN = 32;
  internal const int ROLLBACK = 33;
  internal const int OPTIMIZE = 34;
  internal const int DESCRIBE = 35;
  internal const int SHUTDOWN = 36;
  internal const int IS = 37;
  internal const int AS = 38;
  internal const int ON = 39;
  internal const int IF = 40;
  internal const int TO = 41;
  internal const int NO = 42;
  internal const int ALL = 43;
  internal const int ANY = 44;
  internal const int SET = 45;
  internal const int USE = 46;
  internal const int ASC = 47;
  internal const int OLD = 48;
  internal const int NEW = 49;
  internal const int SQLADD = 50;
  internal const int FOR = 51;
  internal const int ROW = 52;
  internal const int EACH = 53;
  internal const int CALL = 54;
  internal const int BOTH = 55;
  internal const int SOME = 56;
  internal const int FROM = 57;
  internal const int LEFT = 58;
  internal const int DESC = 59;
  internal const int INTO = 60;
  internal const int JOIN = 61;
  internal const int TRIM = 62;
  internal const int VIEW = 63;
  internal const int LOCK = 64;
  internal const int WITH = 65;
  internal const int USER = 66;
  internal const int CAST = 67;
  internal const int LONG = 68;
  internal const int NAME = 69;
  internal const int JAVA = 70;
  internal const int AFTER = 71;
  internal const int START = 72;
  internal const int COUNT = 73;
  internal const int WHERE = 74;
  internal const int CYCLE = 75;
  internal const int CACHE = 76;
  internal const int RIGHT = 77;
  internal const int TABLE = 78;
  internal const int LIMIT = 79;
  internal const int INNER = 80;
  internal const int INDEX = 81;
  internal const int CROSS = 82;
  internal const int OUTER = 83;
  internal const int CHECK = 84;
  internal const int USING = 85;
  internal const int UNION = 86;
  internal const int GRANT = 87;
  internal const int USAGE = 88;
  internal const int SQLRETURN = 89;
  internal const int BEFORE = 90;
  internal const int UNLOCK = 91;
  internal const int ACTION = 92;
  internal const int GROUPS = 93;
  internal const int REVOKE = 94;
  internal const int OPTION = 95;
  internal const int PUBLIC = 96;
  internal const int EXCEPT = 97;
  internal const int IGNORE = 98;
  internal const int SCHEMA = 99;
  internal const int EXISTS = 100;
  internal const int VALUES = 101;
  internal const int HAVING = 102;
  internal const int UNIQUE = 103;
  internal const int SQLCOLUMN = 104;
  internal const int RETURNS = 105;
  internal const int ACCOUNT = 106;
  internal const int LEADING = 107;
  internal const int NATURAL = 108;
  internal const int BETWEEN = 109;
  internal const int TRIGGER = 110;
  internal const int SQLDEFAULT = 111;
  internal const int VARYING = 112;
  internal const int EXECUTE = 113;
  internal const int CALLBACK = 114;
  internal const int MINVALUE = 115;
  internal const int MAXVALUE = 116;
  internal const int FUNCTION = 117;
  internal const int SEQUENCE = 118;
  internal const int RESTRICT = 119;
  internal const int PASSWORD = 120;
  internal const int TRAILING = 121;
  internal const int GROUPBY = 122;
  internal const int ORDERBY = 123;
  internal const int DEFERRED = 124;
  internal const int DISTINCT = 125;
  internal const int LANGUAGE = 126;
  internal const int INCREMENT = 127;
  internal const int PROCEDURE = 128;
  internal const int CHARACTER = 129;
  internal const int IMMEDIATE = 130;
  internal const int INITIALLY = 131;
  internal const int TEMPORARY = 132;
  internal const int INTERSECT = 133;
  internal const int PRIVILEGES = 134;
  internal const int CONSTRAINT = 135;
  internal const int DEFERRABLE = 136;
  internal const int REFERENCES = 137;
  internal const int PRIMARY = 138;
  internal const int FOREIGN = 139;
  internal const int KEY = 140;
  internal const int INDEX_NONE = 141;
  internal const int INDEX_BLIST = 142;
  internal const int GROUPMAX = 143;
  internal const int COLLATE = 144;
  internal const int PRIMARY_STRENGTH = 145;
  internal const int SECONDARY_STRENGTH = 146;
  internal const int TERTIARY_STRENGTH = 147;
  internal const int IDENTICAL_STRENGTH = 148;
  internal const int NO_DECOMPOSITION = 149;
  internal const int CANONICAL_DECOMPOSITION = 150;
  internal const int FULL_DECOMPOSITION = 151;
  internal const int BIT = 152;
  internal const int INT = 153;
  internal const int REAL = 154;
  internal const int CLOB = 155;
  internal const int BLOB = 156;
  internal const int CHAR = 157;
  internal const int TEXT = 158;
  internal const int DATE = 159;
  internal const int TIME = 160;
  internal const int FLOAT = 161;
  internal const int BIGINT = 162;
  internal const int DOUBLE = 163;
  internal const int STRING = 164;
  internal const int BINARY = 165;
  internal const int OBJECT = 166;
  internal const int NUMERIC = 167;
  internal const int DECIMAL = 168;
  internal const int BOOLEAN = 169;
  internal const int TINYINT = 170;
  internal const int INTEGER = 171;
  internal const int VARCHAR = 172;
  internal const int SMALLINT = 173;
  internal const int VARBINARY = 174;
  internal const int TIMESTAMP = 175;
  internal const int LONGVARCHAR = 176;
  internal const int LONGVARBINARY = 177;
  internal const int TRANSACTIONISOLATIONLEVEL = 178;
  internal const int AUTOCOMMIT = 179;
  internal const int READCOMMITTED = 180;
  internal const int READUNCOMMITTED = 181;
  internal const int REPEATABLEREAD = 182;
  internal const int SERIALIZABLE = 183;
  internal const int CASCADE = 184;
  internal const int CURRENT_TIME = 185;
  internal const int CURRENT_DATE = 186;
  internal const int CURRENT_TIMESTAMP = 187;
  internal const int LIKE = 188;
  internal const int REGEX = 189;
  internal const int AND = 190;
  internal const int OR = 191;
  internal const int IN = 192;
  internal const int NOT = 193;
  internal const int NUMBER_LITERAL = 194;
  internal const int STRING_LITERAL = 195;
  internal const int QUOTED_VARIABLE = 196;
  internal const int IDENTIFIER = 197;
  internal const int DOT_DELIMINATED_REF = 198;
  internal const int QUOTED_DELIMINATED_REF = 199;
  internal const int OBJECT_ARRAY_REF = 200;
  internal const int CTALIAS = 201;
  internal const int GLOBVARIABLE = 202;
  internal const int QUOTEDGLOBVARIABLE = 203;
  internal const int PARAMETER_REF = 204;
  internal const int LETTER = 205;
  internal const int DIGIT = 206;

  internal const int DEFAULT = 0;

  internal readonly string[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"*\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<NOTEQ>",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "<BOOLEAN_LITERAL>",
    "\"null\"",
    "<REGEX_LITERAL>",
    "\"drop\"",
    "\"show\"",
    "\"alter\"",
    "\"select\"",
    "\"update\"",
    "\"create\"",
    "\"delete\"",
    "\"insert\"",
    "\"commit\"",
    "\"compact\"",
    "\"explain\"",
    "\"rollback\"",
    "\"optimize\"",
    "\"describe\"",
    "\"shutdown\"",
    "\"is\"",
    "\"as\"",
    "\"on\"",
    "\"if\"",
    "\"to\"",
    "\"no\"",
    "\"all\"",
    "\"any\"",
    "\"set\"",
    "\"use\"",
    "\"asc\"",
    "\"old\"",
    "\"new\"",
    "\"add\"",
    "\"for\"",
    "\"row\"",
    "\"each\"",
    "\"call\"",
    "\"both\"",
    "\"some\"",
    "\"from\"",
    "\"left\"",
    "\"desc\"",
    "\"into\"",
    "\"join\"",
    "\"trim\"",
    "\"view\"",
    "\"lock\"",
    "\"with\"",
    "\"user\"",
    "\"cast\"",
    "\"long\"",
    "\"name\"",
    "\"java\"",
    "\"after\"",
    "\"start\"",
    "\"count\"",
    "\"where\"",
    "\"cycle\"",
    "\"cache\"",
    "\"right\"",
    "\"table\"",
    "\"limit\"",
    "\"inner\"",
    "\"index\"",
    "\"cross\"",
    "\"outer\"",
    "\"check\"",
    "\"using\"",
    "\"union\"",
    "\"grant\"",
    "\"usage\"",
    "\"return\"",
    "\"before\"",
    "\"unlock\"",
    "\"action\"",
    "\"groups\"",
    "\"revoke\"",
    "\"option\"",
    "\"public\"",
    "\"except\"",
    "\"ignore\"",
    "\"schema\"",
    "\"exists\"",
    "\"values\"",
    "\"having\"",
    "\"unique\"",
    "\"column\"",
    "\"returns\"",
    "\"account\"",
    "\"leading\"",
    "\"natural\"",
    "\"between\"",
    "\"trigger\"",
    "\"default\"",
    "\"varying\"",
    "\"execute\"",
    "\"callback\"",
    "\"minvalue\"",
    "\"maxvalue\"",
    "\"function\"",
    "\"sequence\"",
    "\"restrict\"",
    "\"password\"",
    "\"trailing\"",
    "\"group by\"",
    "\"order by\"",
    "\"deferred\"",
    "\"distinct\"",
    "\"language\"",
    "\"increment\"",
    "\"procedure\"",
    "\"character\"",
    "\"immediate\"",
    "\"initially\"",
    "\"temporary\"",
    "\"intersect\"",
    "\"privileges\"",
    "\"constraint\"",
    "\"deferrable\"",
    "\"references\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"index_none\"",
    "\"index_blist\"",
    "\"group max\"",
    "\"collate\"",
    "\"primary_strength\"",
    "\"secondary_strength\"",
    "\"tertiary_strength\"",
    "\"identical_strength\"",
    "\"no_decomposition\"",
    "\"canonical_decomposition\"",
    "\"full_decomposition\"",
    "\"bit\"",
    "\"int\"",
    "\"real\"",
    "\"clob\"",
    "\"blob\"",
    "\"char\"",
    "\"text\"",
    "\"date\"",
    "\"time\"",
    "\"float\"",
    "\"bigint\"",
    "\"double\"",
    "\"string\"",
    "\"binary\"",
    "\"object\"",
    "\"numeric\"",
    "\"decimal\"",
    "\"bool\"",
    "\"tinyint\"",
    "\"integer\"",
    "\"varchar\"",
    "\"smallint\"",
    "\"varbinary\"",
    "\"timestamp\"",
    "\"longvarchar\"",
    "\"longvarbinary\"",
    "\"transaction isolation level\"",
    "\"auto commit\"",
    "\"read committed\"",
    "\"read uncommitted\"",
    "\"repeatable read\"",
    "\"serializable\"",
    "\"cascade\"",
    "\"current_time\"",
    "\"current_date\"",
    "\"current_timestamp\"",
    "\"like\"",
    "\"regex\"",
    "\"and\"",
    "\"or\"",
    "\"in\"",
    "\"not\"",
    "<NUMBER_LITERAL>",
    "<STRING_LITERAL>",
    "<QUOTED_VARIABLE>",
    "<IDENTIFIER>",
    "<DOT_DELIMINATED_REF>",
    "<QUOTED_DELIMINATED_REF>",
    "<OBJECT_ARRAY_REF>",
    "<CTALIAS>",
    "<GLOBVARIABLE>",
    "<QUOTEDGLOBVARIABLE>",
    "\"?\"",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
}
